from django.contrib import admin

from .models import CosteRiesgo,CosteRiesgo2,Stock, Dotaciones,AltasSeguimiento, OfertasProducto, Campana2, MoraDistrito, RVGL, Verificaciones, Caida, Evaluaciontc, Evaluacionpld, Seguimiento, Seguimiento1, FlujOperativo, HipotecaSSFF, HipotecaConce, Moras, AdelantoSueldo, PrestInmediato, AltasEmpresa, AltasSegmento, IncreLinea, Lifemiles, Exoneracion, Forzaje, CampanaWeb, Mapa, DepartamentosWeb, CampanaEfec, CampanaEquifax, Comentario, EfectividadTC, ComentarioBackup

#admin.site.register(Campana) importar model para uso
admin.site.register(Campana2)
admin.site.register(MoraDistrito)
admin.site.register(RVGL)
admin.site.register(Verificaciones)
admin.site.register(Caida)
admin.site.register(Evaluaciontc)
admin.site.register(Evaluacionpld)
admin.site.register(Seguimiento)
admin.site.register(Seguimiento1)
admin.site.register(FlujOperativo)
admin.site.register(HipotecaSSFF)
admin.site.register(HipotecaConce)
admin.site.register(Moras)
admin.site.register(AdelantoSueldo)
admin.site.register(PrestInmediato)
admin.site.register(AltasEmpresa)
admin.site.register(AltasSegmento)
admin.site.register(IncreLinea)
admin.site.register(Lifemiles)
admin.site.register(Exoneracion)
admin.site.register(Forzaje)
admin.site.register(CampanaWeb)
admin.site.register(Mapa)
admin.site.register(DepartamentosWeb)
admin.site.register(CampanaEfec)
#admin.site.register(CampanaLabSeg)
admin.site.register(CampanaEquifax)
admin.site.register(Comentario)
admin.site.register(ComentarioBackup)
admin.site.register(EfectividadTC)
admin.site.register(AltasSeguimiento)
admin.site.register(OfertasProducto)
admin.site.register(Stock)
admin.site.register(Dotaciones)
admin.site.register(CosteRiesgo)
admin.site.register(CosteRiesgo2)
# Register your models here.
