# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_campana', models.CharField(max_length=100)),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('segmento', models.CharField(max_length=20)),
                ('ofertas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
