# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoraDistrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('saldo_stock', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mora_12', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mora_24', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mora_contable', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prima', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
