# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_moradistrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moradistrito',
            name='saldo_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
