# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0003_auto_20160225_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='RVGL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('rvgl', models.CharField(max_length=8)),
                ('seco', models.CharField(max_length=8)),
                ('dictamen', models.CharField(max_length=30)),
                ('analista', models.CharField(max_length=100)),
                ('importe_solic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_eval', models.IntegerField()),
                ('producto_esp', models.CharField(max_length=50)),
                ('territorio_nuevo', models.CharField(max_length=50)),
                ('ejecutivo_cuenta', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('seg_prime', models.CharField(max_length=10)),
                ('sco', models.CharField(max_length=10)),
                ('dictamen_sco', models.CharField(max_length=10)),
                ('dic_buro', models.CharField(max_length=10)),
            ],
        ),
    ]
