# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rvgl'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvgl',
            name='importe_aprob',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
