# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rvgl_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('segmento', models.CharField(max_length=20)),
                ('exonera_ambas', models.IntegerField()),
                ('exonera_solo_vl', models.IntegerField()),
                ('exonera_solo_vd', models.IntegerField()),
                ('requiere_ambas', models.IntegerField()),
                ('exonera_vl_tc', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_adelanto_sueldo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_auto_2da',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_efectivo_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_incr_linea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_pld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_prestamo_inmediato',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_renovado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_subrogacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_tc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_tc_entry_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='monto_veh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_adelanto_sueldo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_auto_2da',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_efectivo_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_incr_linea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_pld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_prestamo_inmediato',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_renovado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_subrogacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_tc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_tc_entry_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='q_veh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campana',
            name='ofertas',
            field=models.IntegerField(default=0),
        ),
    ]
