# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20160319_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('segmento', models.CharField(max_length=20)),
                ('caida', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
