# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0011_auto_20160319_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionpld',
            name='buro',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluaciontc',
            name='buro',
            field=models.CharField(max_length=5),
        ),
    ]
