# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20160319_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionpld',
            name='edad',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluaciontc',
            name='edad',
            field=models.CharField(max_length=5),
        ),
    ]
