# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0013_auto_20160319_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionpld',
            name='sueldo_final',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluaciontc',
            name='sueldo_final',
            field=models.CharField(max_length=20),
        ),
    ]
