# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0014_auto_20160319_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('dic_global', models.CharField(max_length=10)),
                ('dic_buro', models.CharField(max_length=5)),
                ('buro_camp', models.CharField(max_length=20)),
                ('buro_uno', models.CharField(max_length=20)),
                ('segmento', models.CharField(max_length=20)),
                ('origen', models.CharField(max_length=50)),
                ('rng_ing', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=50)),
                ('riesgos', models.CharField(max_length=20)),
                ('soli', models.IntegerField(default=0)),
                ('plazo', models.IntegerField(default=0)),
                ('form', models.IntegerField(default=0)),
                ('facturacion', models.DecimalField(decimal_places=4, default=0, max_digits=4)),
            ],
        ),
    ]
