# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0015_seguimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seguimiento',
        ),
    ]
