# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0018_auto_20160323_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento1',
            name='facturacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
