# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0019_auto_20160323_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujOperativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=5)),
                ('grupo_exoneracion', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
