# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_hipotecassff'),
    ]

    operations = [
        migrations.CreateModel(
            name='HipotecaConce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_form', models.CharField(max_length=10)),
                ('territorio', models.CharField(max_length=30)),
                ('inversion', models.DecimalField(decimal_places=15, default=0, max_digits=18)),
                ('vencida', models.DecimalField(decimal_places=15, default=0, max_digits=18)),
                ('cuotas', models.IntegerField()),
                ('mes', models.CharField(max_length=10)),
            ],
        ),
    ]
