# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_hipotecaconce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre_form', models.CharField(max_length=10)),
                ('mes_form', models.CharField(max_length=10)),
                ('flg_camp', models.CharField(max_length=25)),
                ('flg_uso', models.IntegerField()),
                ('producto', models.CharField(max_length=30)),
                ('ctas', models.IntegerField()),
                ('ctas_uso', models.IntegerField()),
                ('mora6', models.IntegerField()),
                ('mora9', models.IntegerField()),
                ('mora12', models.IntegerField()),
                ('mora18', models.IntegerField()),
                ('mora24', models.IntegerField()),
                ('mora36', models.IntegerField()),
            ],
        ),
    ]
