# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_moras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moras',
            name='mora12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='moras',
            name='mora18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='moras',
            name='mora24',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='moras',
            name='mora36',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='moras',
            name='mora6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='moras',
            name='mora9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
