# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_auto_20160331_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moras',
            name='ctas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='moras',
            name='ctas_uso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
