# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0027_auto_20160331_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_campana', models.CharField(max_length=10)),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('segmento', models.CharField(max_length=20)),
                ('tipo_clie', models.CharField(max_length=20)),
                ('verificacion', models.CharField(max_length=50)),
                ('ofertas', models.IntegerField(default=0)),
                ('q_tc', models.IntegerField(default=0)),
                ('monto_tc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_pld', models.IntegerField(default=0)),
                ('monto_pld', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_veh', models.IntegerField(default=0)),
                ('monto_veh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_subrogacion', models.IntegerField(default=0)),
                ('monto_subrogacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_tc_entry_level', models.IntegerField(default=0)),
                ('monto_tc_entry_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_renovado', models.IntegerField(default=0)),
                ('monto_renovado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_auto_2da', models.IntegerField(default=0)),
                ('monto_auto_2da', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_adelanto_sueldo', models.IntegerField(default=0)),
                ('monto_adelanto_sueldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_efectivo_plus', models.IntegerField(default=0)),
                ('monto_efectivo_plus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_prestamo_inmediato', models.IntegerField(default=0)),
                ('monto_prestamo_inmediato', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('q_incr_linea', models.IntegerField(default=0)),
                ('monto_incr_linea', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
