# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_campana2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdelantoSueldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('rng_buro', models.CharField(max_length=15)),
                ('tipo_importe', models.CharField(max_length=30)),
                ('rng_suelgo', models.CharField(max_length=40)),
                ('flg_prestamo', models.CharField(max_length=20)),
                ('estado_cred', models.CharField(max_length=50)),
                ('ctas', models.IntegerField(default=0)),
                ('fact', models.IntegerField(default=0)),
                ('mora', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AltasEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=30)),
                ('m1', models.IntegerField(default=0)),
                ('m2', models.IntegerField(default=0)),
                ('m3', models.IntegerField(default=0)),
                ('m4', models.IntegerField(default=0)),
                ('m5', models.IntegerField(default=0)),
                ('m6', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AltasSegmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrestInmediato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('rng_ingreso', models.CharField(max_length=30)),
                ('segmento', models.CharField(max_length=10)),
                ('rng_buro', models.CharField(max_length=20)),
                ('subproducto', models.CharField(max_length=60)),
                ('estado_cred', models.CharField(max_length=50)),
                ('ctas', models.IntegerField(default=0)),
                ('fact', models.IntegerField(default=0)),
                ('mora12', models.IntegerField(default=0)),
                ('mora6', models.IntegerField(default=0)),
            ],
        ),
    ]
