# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_auto_20160406_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adelantosueldo',
            name='ctas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='prestinmediato',
            name='ctas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
