# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_auto_20160413_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncreLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('buro', models.CharField(max_length=20)),
                ('segmento', models.CharField(max_length=20)),
                ('rng_sueldo', models.CharField(max_length=30)),
                ('ctas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cantidad', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
    ]
