# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0033_increlinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='increlinea',
            name='ctas',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
