# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_auto_20160413_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifemiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('buro', models.CharField(max_length=20)),
                ('buro1', models.CharField(max_length=20)),
                ('rng_ing', models.CharField(max_length=20)),
                ('segmento', models.CharField(max_length=20)),
                ('ctas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ctas_saldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mora6_60', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mora12_60', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imp_sol', models.DecimalField(decimal_places=8, max_digits=12)),
                ('inv', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='increlinea',
            name='lifemiles',
            field=models.IntegerField(default=0),
        ),
    ]
