# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0035_auto_20160415_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='moras',
            name='mora4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='moras',
            name='segmento',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
