# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0037_auto_20160415_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifemiles',
            name='mora12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='lifemiles',
            name='mora6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
