# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_exoneracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forzaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('dic_global', models.CharField(max_length=10)),
                ('producto', models.CharField(max_length=30)),
                ('form', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
