# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0045_auto_20160610_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentosweb',
            name='documento',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='departamentosweb',
            name='fecha_envio',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='departamentosweb',
            name='fuente',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='departamentosweb',
            name='plastico_tc',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='departamentosweb',
            name='segmento',
            field=models.CharField(max_length=25),
        ),
    ]
