# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0048_auto_20160620_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentosweb',
            name='semana',
            field=models.IntegerField(default=0),
        ),
    ]
