# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-18 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0049_departamentosweb_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='campanaweb',
            name='fecha_desde',
        ),
        migrations.RemoveField(
            model_name='campanaweb',
            name='fecha_hasta',
        ),
        migrations.AddField(
            model_name='campanaweb',
            name='num_eval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campanaweb',
            name='pld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campanaweb',
            name='pld_formal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='campanaweb',
            name='tdc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campanaweb',
            name='tdc_formal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
