# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0050_auto_20160718_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaEfec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento0', models.CharField(max_length=10)),
                ('segmento1', models.CharField(max_length=50)),
                ('exo_ambas', models.CharField(max_length=10)),
                ('exo_solovd', models.CharField(max_length=10)),
                ('exo_solovl', models.CharField(max_length=10)),
                ('requiere_ambas', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('total_apro', models.CharField(max_length=10)),
                ('form', models.CharField(max_length=10)),
                ('porc_form', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CampanaLabSeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro0', models.CharField(max_length=40)),
                ('filtro1', models.CharField(max_length=40)),
                ('filtro2', models.CharField(max_length=50)),
                ('form', models.CharField(max_length=10)),
                ('total_form', models.CharField(max_length=10)),
                ('porc_form', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ResumenWeb',
        ),
    ]
