# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0051_auto_20160719_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanaefec',
            name='segmento0',
            field=models.CharField(max_length=50),
        ),
    ]
