# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0053_campanaefec_id_efec'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanaefec',
            name='mes',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='semana',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='campanaweb',
            name='mes',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='campanaweb',
            name='semana',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
