# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-21 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0054_auto_20160720_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanaweb',
            name='pld',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='campanaweb',
            name='tdc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
