# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0055_auto_20160721_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaEquifax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equifax', models.IntegerField(default=0)),
                ('filtro0', models.CharField(max_length=40)),
                ('filtro1', models.CharField(max_length=40)),
                ('ambas', models.CharField(max_length=10)),
                ('solovd', models.CharField(max_length=10)),
                ('solovl', models.CharField(max_length=10)),
                ('req', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='campanaefec',
            name='exo_ambas',
        ),
        migrations.RemoveField(
            model_name='campanaefec',
            name='exo_solovd',
        ),
        migrations.RemoveField(
            model_name='campanaefec',
            name='exo_solovl',
        ),
        migrations.RemoveField(
            model_name='campanaefec',
            name='porc_form',
        ),
        migrations.RemoveField(
            model_name='campanaefec',
            name='requiere_ambas',
        ),
        migrations.RemoveField(
            model_name='campanaefec',
            name='total',
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='form_ambas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='form_req',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='form_solovd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='form_solovl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='form_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='sol_ambas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='sol_req',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='sol_solovd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='sol_solovl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campanaefec',
            name='sol_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='campanaefec',
            name='form',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='campanaefec',
            name='total_apro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
