# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-09 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0056_auto_20160722_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='moras',
            name='cat_persona',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='cat_persona',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
