# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0057_auto_20160809_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifemiles',
            name='mora9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
