# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0058_lifemiles_mora9'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='vinculo',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
