# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0059_mapa_vinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvgl',
            name='base_rvgl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rvgl',
            name='base_sco',
            field=models.IntegerField(default=0),
        ),
    ]
