# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0060_auto_20160905_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanaweb',
            name='pld_formal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='campanaweb',
            name='tdc_formal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
