# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0061_auto_20160915_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='moras',
            name='buro_camp',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='moras',
            name='buro_uno',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
