# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0063_auto_20160923_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forzaje',
            old_name='trimestre',
            new_name='trimestre_form',
        ),
    ]
