# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0064_auto_20160926_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento1',
            old_name='trimestre',
            new_name='trimestre_form',
        ),
    ]
