# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0065_auto_20160926_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
                ('comentario', models.CharField(max_length=500)),
                ('usuario', models.CharField(max_length=20)),
            ],
        ),
    ]
