# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0066_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfectividadTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_campana', models.CharField(max_length=10)),
                ('trimestre', models.CharField(max_length=10)),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('buro', models.CharField(max_length=10)),
                ('segmento', models.CharField(max_length=20)),
                ('tipo_clie', models.CharField(max_length=30)),
                ('verificacion', models.CharField(max_length=50)),
                ('contratado', models.CharField(max_length=60)),
                ('total_form', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_form', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_ofer', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
