# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0067_efectividadtc'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='tiempo',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(default=0, max_length=3500),
        ),
    ]
