# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0068_auto_20161003_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltasSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buro', models.CharField(max_length=10)),
                ('codempresa', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=20)),
                ('mes_alta', models.CharField(max_length=10)),
                ('rg_edad', models.CharField(max_length=20)),
                ('cat_cliente', models.CharField(max_length=30)),
                ('rg_ingreso', models.CharField(max_length=30)),
                ('ctas', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='OfertasProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('ofertas_tc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_tc', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ofertas_pld', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_pld', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ofertas_veh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_veh', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ofertas_sub', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_sub', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ofertas_ep', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_ep', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ofertas_il', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_il', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ofertas_ads', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_ads', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
    ]
