# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0069_altasseguimiento_ofertasproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='adelantosueldo',
            name='laboral',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='adelantosueldo',
            name='rng_buro_act',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='increlinea',
            name='buro_act',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='increlinea',
            name='ctas_uso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='increlinea',
            name='empleado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='increlinea',
            name='flg_uso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='increlinea',
            name='laboral',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='increlinea',
            name='mora12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='prestinmediato',
            name='laboral',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='increlinea',
            name='buro',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='increlinea',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='increlinea',
            name='ctas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='increlinea',
            name='mes_vigencia',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='increlinea',
            name='rng_sueldo',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='increlinea',
            name='segmento',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
