# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0070_auto_20161012_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento1',
            name='dic_buro',
        ),
        migrations.RemoveField(
            model_name='seguimiento1',
            name='dic_global',
        ),
        migrations.RemoveField(
            model_name='seguimiento1',
            name='soli',
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='canal_digital',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='ctas_uso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='digital',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='flg_lifemiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='ltv',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='mora12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='mora18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='mora24',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='mora36',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='mora4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='mora4_60',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='mora6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='mora9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
