# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0071_auto_20161014_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento1',
            old_name='ctas_uso',
            new_name='ctas',
        ),
    ]
