# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0072_auto_20161014_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='forzaje',
            name='periodo',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='seguimiento1',
            name='periodo',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
