# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0074_comentario_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
                ('comentario', models.CharField(default=0, max_length=3500)),
                ('usuario', models.CharField(max_length=20)),
                ('tiempo', models.CharField(default=0, max_length=50)),
                ('hora', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
