# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0076_comentario_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariobackup',
            name='titulo',
            field=models.CharField(default=0, max_length=400),
        ),
    ]
