# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0077_comentariobackup_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento1',
            name='cluster',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
