# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0078_seguimiento1_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
                ('trimestre_form', models.CharField(max_length=10)),
                ('mes_vigencia', models.CharField(max_length=10)),
                ('producto', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=50)),
                ('riesgos', models.CharField(max_length=20)),
                ('rng_ing', models.CharField(max_length=20)),
                ('segmento', models.CharField(max_length=20)),
                ('cat_persona', models.CharField(max_length=50)),
                ('buro_camp', models.CharField(max_length=20)),
                ('cluster', models.CharField(max_length=50)),
                ('digital', models.CharField(max_length=5)),
                ('canal_digital', models.CharField(max_length=30)),
                ('flg_lifemiles', models.CharField(max_length=5)),
                ('form', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ctas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('facturacion', models.DecimalField(decimal_places=8, max_digits=12)),
                ('mora4_60', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mora6', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mora9', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mora12', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mora24', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mora36', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
