# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0079_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='mora18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
