# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0080_seguimiento_mora18'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dotaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmes', models.CharField(default=0, max_length=10)),
                ('producto', models.CharField(default=0, max_length=20)),
                ('subproducto', models.CharField(default=0, max_length=40)),
                ('campana', models.CharField(default=0, max_length=50)),
                ('riesgo', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dotacion', models.DecimalField(decimal_places=4, max_digits=20)),
                ('mora', models.DecimalField(decimal_places=4, max_digits=20)),
                ('salidas', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmes', models.CharField(default=0, max_length=10)),
                ('flg_campana', models.CharField(default=0, max_length=50)),
                ('trimestre', models.CharField(max_length=10)),
                ('producto', models.CharField(default=0, max_length=20)),
                ('subproducto', models.CharField(default=0, max_length=40)),
                ('campana', models.CharField(default=0, max_length=50)),
                ('ctas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fact', models.DecimalField(decimal_places=8, max_digits=14)),
                ('inv', models.DecimalField(decimal_places=8, max_digits=14)),
                ('atrasada', models.DecimalField(decimal_places=8, max_digits=14)),
            ],
        ),
    ]
