# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0081_dotaciones_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosteRiesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(default=0, max_length=20)),
                ('codmes', models.CharField(default=0, max_length=10)),
                ('m6', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m9', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m12', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CosteRiesgo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmes', models.CharField(default=0, max_length=10)),
                ('m1', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m2', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m3', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m4', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m5', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m6', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m7', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m8', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m9', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m10', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m11', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('m12', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
            ],
        ),
    ]
