# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0082_costeriesgo_costeriesgo2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costeriesgo',
            old_name='m12',
            new_name='m12_c',
        ),
        migrations.RenameField(
            model_name='costeriesgo',
            old_name='m6',
            new_name='m12_t',
        ),
        migrations.RenameField(
            model_name='costeriesgo',
            old_name='m9',
            new_name='m12_u',
        ),
        migrations.AddField(
            model_name='costeriesgo',
            name='m6_c',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='costeriesgo',
            name='m6_t',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='costeriesgo',
            name='m6_u',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='costeriesgo',
            name='m9_c',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='costeriesgo',
            name='m9_t',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='costeriesgo',
            name='m9_u',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='costeriesgo2',
            name='producto',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='costeriesgo2',
            name='subproducto',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
