# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0084_seguimientoter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTelefonica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosecha', models.CharField(max_length=10)),
                ('rng_edad', models.CharField(max_length=20)),
                ('rng_buro', models.CharField(max_length=20)),
                ('cluster', models.CharField(max_length=50)),
                ('rng_financiar', models.CharField(max_length=20)),
                ('capital_financiar', models.DecimalField(decimal_places=4, max_digits=16)),
                ('form', models.DecimalField(decimal_places=4, max_digits=16)),
                ('m12', models.DecimalField(decimal_places=4, max_digits=16)),
                ('m6', models.DecimalField(decimal_places=4, max_digits=16)),
                ('m3', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='StockTelefonica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmes', models.CharField(max_length=10)),
                ('mesform', models.CharField(max_length=10)),
                ('tipo_operacion', models.CharField(max_length=20)),
                ('clasificacion_final', models.DecimalField(decimal_places=4, max_digits=8)),
                ('maduracion', models.DecimalField(decimal_places=4, max_digits=8)),
                ('con_atraso', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ctas', models.DecimalField(decimal_places=4, max_digits=16)),
                ('ctas_atraso', models.DecimalField(decimal_places=4, max_digits=16)),
                ('ctas_30', models.DecimalField(decimal_places=4, max_digits=16)),
                ('deuda', models.DecimalField(decimal_places=4, max_digits=16)),
                ('mora_30', models.DecimalField(decimal_places=4, max_digits=16)),
                ('vigente', models.DecimalField(decimal_places=4, max_digits=16)),
                ('vencido', models.DecimalField(decimal_places=4, max_digits=16)),
                ('judicial', models.DecimalField(decimal_places=4, max_digits=16)),
                ('ref_vigente', models.DecimalField(decimal_places=4, max_digits=16)),
                ('ref_vencido', models.DecimalField(decimal_places=4, max_digits=16)),
                ('ref_judicial', models.DecimalField(decimal_places=4, max_digits=16)),
                ('prov_gen', models.DecimalField(decimal_places=4, max_digits=16)),
                ('prov_esp', models.DecimalField(decimal_places=4, max_digits=16)),
                ('prov_pro', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
    ]
