# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-31 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion', '0085_formtelefonica_stocktelefonica'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltasTarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=50)),
                ('segmento', models.CharField(max_length=50)),
                ('riesgo_cliente', models.CharField(max_length=100)),
                ('tipo_oferta', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=200)),
                ('sueldo_final', models.CharField(max_length=200)),
                ('buro', models.CharField(max_length=100)),
                ('ofertas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('altas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('altas_dia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_alta', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='departamentosweb',
            name='oferta_pld',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='departamentosweb',
            name='oferta_tc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rvgl',
            name='importe_aprob',
            field=models.FloatField(default=0),
        ),
    ]
